kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
  labels:
    app.kubernetes.io/name: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  app-config-rhdh.yaml: |
    app:
      title: Red Hat Developer Hub
      baseUrl: https://{{ .Values.backstage.host }}

    signInPage: oidc
    auth:
      session:
        secret: ${BACKEND_SECRET}
      environment: production
      providers:
        oidc:
          production:
            prompt: auto
            metadataUrl: https://{{ .Values.keycloak.host }}/realms/{{ .Values.keycloak.realm }}/.well-known/openid-configuration
            clientId: ${OAUTH_CLIENT_ID}
            clientSecret: ${OAUTH_CLIENT_SECRET}
            signIn:
              resolvers:
                - resolver: preferredUsernameMatchingUserEntityName

    
    backend:
      baseUrl: https://{{ .Values.backstage.host }}
      listen:
        port: 7007
        host: 0.0.0.0
      actions:
        pluginSources:
          - software-catalog-mcp-tool
          - techdocs-mcp-tool
      auth:
        externalAccess:
          - type: static
            options:
              token: ${BACKEND_SECRET}
              subject: orchestrator


    integrations:
      gitlab:
        - apiBaseUrl: https://{{ .Values.gitlab.host }}/api/v4
          baseUrl: https://{{ .Values.gitlab.host }}
          host: {{ .Values.gitlab.host }}
          token: ${GITLAB_TOKEN}

    catalog:
      rules:
        - allow: [Component, System, API, Resource, Location, Template, Domain]
      locations:
        - type: url
          target: https://github.com/evanshortiss/from-ai-hype-to-platform-reality/blob/main/catalog/catalog-info.yaml
          rules:
            - allow: [Component, System, API, Resource, Location, Template, Domain, User, Group]
      providers:
        keycloakOrg:
          default:
            baseUrl: https://{{ .Values.keycloak.host }}
            realm: {{ .Values.keycloak.realm }}
            loginRealm: {{ .Values.keycloak.loginRealm }}
            clientId: ${KEYCLOAK_PLUGIN_CLIENT_ID}
            clientSecret: ${KEYCLOAK_PLUGIN_CLIENT_SECRET}
            schedule:
              frequency: { minutes: 2 }
              timeout: { minutes: 1 }
              initialDelay: { seconds: 15 }
        gitlab:
          gitlab:
            host: {{ .Values.gitlab.host }}
            branch: main
            fallbackBranch: main
            entityFilename: catalog-info.yaml
            schedule:
              frequency: { minutes: 5 }
              timeout: { minutes: 3 }

    argocd:
      appLocatorMethods:
        - type: config
          instances:
            - name: main
              url: https://{{ .Values.argocd.host }}
              username: admin
              password: ${ARGOCD_PASSWORD}

    kubernetes:
      serviceLocatorMethod:
        type: multiTenant
      clusterLocatorMethods:
        - clusters:
            - name: dev-cluster
              url: {{ .Values.kubernetes.apiUrl }}
              authProvider: serviceAccount
              skipTLSVerify: true
              serviceAccountToken: ${KUBERNETES_SA_TOKEN}
          type: config
      customResources:
        - group: tekton.dev
          apiVersion: v1beta1
          plural: pipelineruns
        - group: tekton.dev
          apiVersion: v1beta1
          plural: taskruns
