apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lightspeed-secrets
  namespace: rhdh
  labels:
    app.kubernetes.io/name: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: lightspeed-secrets
    creationPolicy: Owner
  data:
    - secretKey: LLM_SERVER_URL
      remoteRef:
        key: secrets/litellm/credentials
        property: base_url
    - secretKey: LLM_SERVER_TOKEN
      remoteRef:
        key: secrets/litellm/credentials
        property: api_key
