apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth-client
  namespace: rhdh
  labels:
    app.kubernetes.io/name: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: oauth-client
    creationPolicy: Owner
  data:
    - secretKey: OAUTH_CLIENT_ID
      remoteRef:
        key: secrets/keycloak/client-secret
        property: clientId
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: secrets/keycloak/client-secret
        property: clientSecret
    - secretKey: KEYCLOAK_PLUGIN_CLIENT_ID
      remoteRef:
        key: secrets/keycloak/client-secret
        property: pluginClientId
    - secretKey: KEYCLOAK_PLUGIN_CLIENT_SECRET
      remoteRef:
        key: secrets/keycloak/plugin-client-secret
        property: value
