apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-orchestrator-token
  namespace: rhdh
  labels:
    app.kubernetes.io/name: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: backstage-orchestrator-token
    creationPolicy: Owner
  data:
    - secretKey: ORCHESTRATOR_TOKEN
      remoteRef:
        key: secrets/rhdh/orchestrator-token
        property: value
