kind: Secret
apiVersion: v1
metadata:
  name: backstage-dynamic-plugins-npmrc
  namespace: rhdh
  labels:
    app.kubernetes.io/name: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
stringData:
  .npmrc: '@redhat:registry=https://npm.registry.redhat.com'
type: Opaque
